Added -l and -s command line arguments to raidlindex.

diff --git a/raidlindex b/raidlindex
--- a/raidlindex
+++ b/raidlindex
@@ -1,13 +1,40 @@
 #!/bin/bash
 
 ! which adb > /dev/null && echo "Could not find adb in path." && exit 1
-[ ! -z $1 ] && dev="-s $1"
+
+dev=""
+lst=""
+
+usage() {
+    echo "Usage: raidlindex [-l | -s <serial number>]" > /dev/stderr
+}
+
+while getopts ":s:l" opt; do
+    case $opt in
+        a)
+            dev="-s $OPTARG"
+            ;;
+        l)
+            lst="-l"
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            usage
+            exit 1
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
+    esac
+done
 
 services=$(adb shell raidl list | tail -n +2 | awk '{print $2}' | tr -d ':')
 
 for s in $services; do 
     echo -n "Dumping AIDL for $s... "
-    adb $dev shell "raidl iface $s 2> /dev/null" > $s.aidl
+    adb $dev shell "raidl iface $lst $s 2> /dev/null" > $s.aidl
     if [ ! -s $s.aidl ]; then
         rm $s.aidl
         echo "FAIL"
